// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_F_and_B_cpp
Rcpp::List get_F_and_B_cpp(Rcpp::List kernels, double tau, Rcpp::List neighbors, Rcpp::List kernels_partial_inverse);
RcppExport SEXP _ensembleDownscaleR_get_F_and_B_cpp(SEXP kernelsSEXP, SEXP tauSEXP, SEXP neighborsSEXP, SEXP kernels_partial_inverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type kernels(kernelsSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type kernels_partial_inverse(kernels_partial_inverseSEXP);
    rcpp_result_gen = Rcpp::wrap(get_F_and_B_cpp(kernels, tau, neighbors, kernels_partial_inverse));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_draw_spatial_nngp_cpp
NumericVector mcmc_draw_spatial_nngp_cpp(NumericVector spatial_effect, double sigma2, List neighbors, List neighbors_inverse, List pos_in_neighbors, List B_s, NumericVector F_s, NumericVector covariate_sums, NumericVector resid_sums);
RcppExport SEXP _ensembleDownscaleR_mcmc_draw_spatial_nngp_cpp(SEXP spatial_effectSEXP, SEXP sigma2SEXP, SEXP neighborsSEXP, SEXP neighbors_inverseSEXP, SEXP pos_in_neighborsSEXP, SEXP B_sSEXP, SEXP F_sSEXP, SEXP covariate_sumsSEXP, SEXP resid_sumsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type spatial_effect(spatial_effectSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< List >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< List >::type neighbors_inverse(neighbors_inverseSEXP);
    Rcpp::traits::input_parameter< List >::type pos_in_neighbors(pos_in_neighborsSEXP);
    Rcpp::traits::input_parameter< List >::type B_s(B_sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type F_s(F_sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type covariate_sums(covariate_sumsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type resid_sums(resid_sumsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_draw_spatial_nngp_cpp(spatial_effect, sigma2, neighbors, neighbors_inverse, pos_in_neighbors, B_s, F_s, covariate_sums, resid_sums));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ensembleDownscaleR_get_F_and_B_cpp", (DL_FUNC) &_ensembleDownscaleR_get_F_and_B_cpp, 4},
    {"_ensembleDownscaleR_mcmc_draw_spatial_nngp_cpp", (DL_FUNC) &_ensembleDownscaleR_mcmc_draw_spatial_nngp_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_ensembleDownscaleR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
