# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_F_and_B_cpp <- function(kernels, tau, neighbors, kernels_partial_inverse) {
    .Call(`_ensembleDownscaleR_get_F_and_B_cpp`, kernels, tau, neighbors, kernels_partial_inverse)
}

mcmc_draw_spatial_nngp_cpp <- function(spatial_effect, sigma2, neighbors, neighbors_inverse, pos_in_neighbors, B_s, F_s, covariate_sums, resid_sums) {
    .Call(`_ensembleDownscaleR_mcmc_draw_spatial_nngp_cpp`, spatial_effect, sigma2, neighbors, neighbors_inverse, pos_in_neighbors, B_s, F_s, covariate_sums, resid_sums)
}

